/**
 * @ai-impostor/contracts — chain config + generated ABI/address artifacts.
 *
 * The ABI + deployed address are regenerated in M2 from the Foundry build and
 * `contracts/deployments/10143.json`. The placeholders below keep web/server
 * type-checking before the contract is deployed; M2 replaces them.
 */
export * from "./chain.js";

/**
 * Canonical EIP712 type string for the `Settlement` struct the ImpostorEscrow
 * contract signs/verifies. Mirrored here so server/web can reference the escrow
 * EIP712 contract without importing the Solidity source.
 *
 * MUST stay byte-for-byte identical to:
 *   - packages/shared/src/settlement.ts → SETTLEMENT_TYPE_STRING
 *     (derived from SETTLEMENT_EIP712_TYPES; pinned by settlement.test.ts)
 *   - contracts/src/ImpostorEscrow.sol → SETTLEMENT_TYPEHASH (the keccak256 input)
 * Changing field order/names/types in any one without the others is a release blocker.
 */
export const SETTLEMENT_TYPE_STRING =
  "Settlement(uint256 gameId,address[] survivors,uint256[] payouts,uint256 houseAmount,bytes32 resultRoot)" as const;

/**
 * Deployed singleton address.
 * PLACEHOLDER — regenerated by the M2 deploy → contracts/deployments/10143.json.
 */
export const ESCROW_ADDRESS: `0x${string}` =
  "0x0000000000000000000000000000000000000000";

/**
 * ImpostorEscrow ABI.
 * PLACEHOLDER — regenerated from `forge build` artifacts in M2. Kept empty (but
 * typed `as const`) so web/server type-check against the package shape today.
 */
export const escrowAbi = [] as const;
