[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"

[invariant]
runs = 1024

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[profile.monad-testnet]
eth_rpc_url = "${MONAD_TESTNET_RPC_URL}"
chain_id = 10_143
